### ISSUE TITLE
Error running against local solution

### ISSUE THREAD

**Issue by mattwoberts** [jerriep/dotnet-outdated#10]
I'm afraid I can't share the project file(s) with you - just dumping this here for now:

```
» 
Analyzing packages...
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetOutdated.ReportingExtensions.<>c.<DetermineColumnWidths>b__0_4(ReportedPackage p) in C:\projects\dotnet-outdated\src\DotNetOutdated\ReportingExtensions.cs:line 13
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at DotNetOutdated.ReportingExtensions.DetermineColumnWidths(List`1 packages) in C:\projects\dotnet-outdated\src\DotNetOutdated\ReportingExtensions.cs:line 13
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 106
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 38
```

**Comment by mattwoberts** [comment]
Related to this I guess?

https://github.com/jerriep/dotnet-outdated/issues/7

**Comment by jerriep** [comment]
Hey @mattwoberts , version 0.2.0 should solve your error message. Update using the following command:

```
dotnet tool update dotnet-outdated -g
```

I hope to address the issue of private feeds in version 0.3.0

**Comment by mattwoberts** [comment]
Cheers for that 👍

**Comment by jerriep** [comment]
@mattwoberts Version 0.3.0 should pick up all package feeds you have configured correctly. Would you mind giving it a shot and see if it works with your private MyGet feed?
