### ISSUE TITLE
Does not work with secured feeds

### ISSUE THREAD

**Issue by damianh** [jerriep/dotnet-outdated#22]
When run for the first time on a project received the below exception.

```
C:\dev\[REMOVED]\src [netstandard +4 ~15 -0 !]> dotnet outdated
» [REMOVED]
  [.NETFramework,Version=v4.6.1]
  Microsoft.AspNetCore.Mvc ...
Unhandled Exception: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://[REMOVED].myget.org/F/ci/api/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at DotNetOutdated.Services.NuGetPackageInfoService.FindResourceForSource(Uri source) in C:\projects\dotnet-outdated\src\DotNetOutdated\Services\NuGetPackageInfoService.cs:line 36
   at DotNetOutdated.Services.NuGetPackageInfoService.GetAllVersions(String package, List`1 sources) in C:\projects\dotnet-outdated\src\DotNetOutdated\Services\NuGetPackageInfoService.cs:line 49
   at DotNetOutdated.Services.NuGetPackageResolutionService.ResolvePackageVersions(String package, List`1 sources, VersionRange currentVersionRange, VersionLock versionLock, PrereleaseReporting prerelease) in C:\projects\dotnet-outdated\src\DotNetOutdated\Services\NuGetPackageResolutionService.cs:line 21
   at DotNetOutdated.Program.ReportDependency(IConsole console, Dependency dependency, List`1 sources, Int32 indentLevel) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 161
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 122
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 48
```

**Comment by jerriep** [comment]
@damianh Yes it seems there is a current issue with using feeds which require Basic authentication as also mentioned in #8.

For now, the workaround is to use the pre-authenticated MyGet URL.

**Comment by jerriep** [comment]
@damianh I have pushed version 1.2.0 to NuGet which handles secure feeds much better. Please read the [working with secure feeds](https://github.com/jerriep/dotnet-outdated#working-with-secure-feeds) section in the readme.

**Comment by damianh** [comment]
Lovely!

**Comment by svdoever** [comment]
Any idea how to handle NuGet feed from DevOps when two-factor authentication is used?

**Comment by jerriep** [comment]
@svdoever No, I do not. Try reaching out to the DevOps support and find out from them whether there is a way around that. Perhaps they have some sort of permalink URL linked to your specific account that you can use.

**Comment by svdoever** [comment]
Ok thank, wil try to contact them. I will try to add a step to the DevOps build pipeline, maybe that in that case we are running in the correct context...

**Comment by jerriep** [comment]
@svdoever MyGet has a concept called [pre-authenticated feeds](https://docs.myget.org/docs/reference/feed-endpoints). Maybe Azure DevOps has something similar?
