### ISSUE TITLE
Unhandled NullReferenceException

### ISSUE THREAD

**Issue by vilinski** [jerriep/dotnet-outdated#245]
Steps to reproduce:

```
$ git clone https://github.com/PragmaticFlow/NBomber.Sinks.InfluxDB
...
$ cd NBomber.Sinks.InfluxDB
$ dotnet --version
3.1.100
$ dotnet tool list -g | grep outdated
dotnet-outdated          2.8.0            dotnet-outdated
$ dotnet outdated
Analyzing project and restoring packages...Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetOutdated.Core.Services.ProjectAnalysisService.AnalyzeProject(String projectPath, Boolean includeTransitiveDependencies, Int32 transitiveDepth) in C:\projects\dotnet-outdated\src\DotNetOutdated.Core\Services\ProjectAnalysisService.cs:line 49
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 163
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 116
```

**Comment by jerriep** [comment]
@vilinski You need to give more information than that. If you have more info to share, feel free to reopen

**Comment by vilinski** [comment]
yes sorry, clicked enter to early )
