### ISSUE TITLE
Unhandled Exception in 1.1.0

### ISSUE THREAD

**Issue by PaitoAnderson** [jerriep/dotnet-outdated#26]
Let me know if you want any more details. Thanks!

```
» WebHost.Library
  [.NETStandard,Version=v2.0]
  AngleSharp 0.9.9.2
  HangFire.Core...
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetOutdated.Services.NuGetPackageResolutionService.ResolvePackageVersions(String packageName, NuGetVersion referencedVersion, List`1 sources, VersionRange currentVersionRange, VersionLock versionLock, PrereleaseReporting prerelease, NuGetFramework targetFrameworkName) in C:\projects\dotnet-outdated\src\DotNetOutdated\Services\NuGetPackageResolutionService.cs:line 22
   at DotNetOutdated.Program.ReportDependency(IConsole console, Dependency dependency, VersionRange versionRange, List`1 sources, Int32 indentLevel, TargetFramework targetFramework) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 172
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 126
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 55
```

**Comment by jerriep** [comment]
@PaitoAnderson Any chance you can post the offending `csproj` here? Just the project file - I do not need any of the source code.

**Comment by BradBarnich** [comment]
We ran into this too (when running with `-t`), but the offending package was privately hosted. So likely a variant of #22
