### ISSUE TITLE
Add output redirection support

### ISSUE THREAD

**Issue by shatl** [jerriep/dotnet-outdated#28]
Program output redirection does not work.

Please add an option to output as plain text (no color)

```
C:\Work\proj\src>dotnet-outdated -i -td 1 | find "Moq"

Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at DotNetOutdated.Program.ClearCurrentConsoleLine() in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 227
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 114
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 60
```

*Version:* 1.2.0-rtm.61+19ab4273e7c29adf600f06e312dede25333ac14b

**Comment by jerriep** [comment]
Version 2.0.0 is now available on NuGet which resolves this issue:
https://www.nuget.org/packages/dotnet-outdated/2.0.0

**Comment by shatl** [comment]
Thanks!
