### ISSUE TITLE
The argument of -pre is required even though it should default to Auto

### ISSUE THREAD

**Issue by Happypig375** [jerriep/dotnet-outdated#300]
From https://github.com/verybadcat/CSharpMath/runs/579196760,
Command: `dotnet outdated -pre -u CSharpMath.Xaml.Tests.NuGet`
```
Unhandled exception. McMaster.Extensions.CommandLineUtils.CommandParsingException: Invalid value specified for pre-release. Allowed values are: Auto, Always, Never.
43
 ---> System.FormatException: Invalid value specified for pre-release. Allowed values are: Auto, Always, Never.
44
   at McMaster.Extensions.CommandLineUtils.Abstractions.EnumParser.<>c__DisplayClass0_0.<Create>b__0(String argName, String value, CultureInfo culture)
45
   at McMaster.Extensions.CommandLineUtils.Abstractions.ValueParser.DelegatingValueParser`1.Parse(String argName, String value, CultureInfo culture)
46
   at McMaster.Extensions.CommandLineUtils.Abstractions.ValueParser.DelegatingValueParser.Parse(String argName, String value, CultureInfo culture)
47
   at McMaster.Extensions.CommandLineUtils.Abstractions.ValueParserProvider.GenericParserAdapter`1.McMaster.Extensions.CommandLineUtils.Abstractions.IValueParser.Parse(String argName, String value, CultureInfo culture)
48
   at McMaster.Extensions.CommandLineUtils.Conventions.OptionAttributeConventionBase`1.<>c__DisplayClass0_1.<AddOption>b__1(ParseResult _)
49
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.HandleParseResult(ParseResult parseResult)
50
   --- End of inner exception stack trace ---
51
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.HandleParseResult(ParseResult parseResult)
52
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication`1.HandleParseResult(ParseResult parseResult)
53
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
54
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
55
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
56
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 119
```

**Comment by jnm2** [comment]
@Happypig375 An option is leaving out `-pre` because it defaults to `Auto`.

**Comment by jerriep** [comment]
@Happypig375  The error message tells you what to do. Specify the correct value for the `-pre` option and the error will go away.
