### ISSUE TITLE
IOException thrown when ran inside Package Manager Console

### ISSUE THREAD

**Issue by samjudson** [jerriep/dotnet-outdated#39]
Hi

I get an exception throw on line 225 of Program.cs (`int currentLineCursor = Console.CursorTop;`) when I run the command inside the Package Manager Console inside of Visual Studio.

```
System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DotNetOutdated.Program.ClearCurrentConsoleLine() in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 225
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 114
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 60
```

It works fine if run inside a separate Powershell window, or a Windows Command Prompt window.

**Comment by jerriep** [comment]
Yeah, I think Package Manager Console is not a "proper" console with all the features a normal console should have. I will investigate, but I am not sure this is something I would be willing to put the time and effort into fixing.

**Comment by samjudson** [comment]
I think just wrapping the offending lines in a try/catch usually does the trick ;)

**Comment by jerriep** [comment]
Running the command from a proper console also does the trick 😉

**Comment by jtsom** [comment]
A data point - trying to run the command in a Git Bash window shows the same exception. (I have this set as my default in VS Code, so it limits use of the command - having to launch Powershell or a cmd window just to run it.)

**Comment by jerriep** [comment]
Interesting. I did not use Git Bash, only Windows 10 Bash where it worked successfully.

In any case, there is work coming down the pipeline which changes the way the progress update is being handled and will probably make this issue not applicable anymore. Therefore, this is not something I will give attention to now.

**Comment by jerriep** [comment]
The test for output redirection I did in 44f41c25989d79912a6bbbba06d791bf406ca708 fixed this as well.

**Comment by jerriep** [comment]
Version 2.0.0 is now available on NuGet which resolves this issue:
https://www.nuget.org/packages/dotnet-outdated/2.0.0
