### ISSUE TITLE
IOException thrown when piping output to a file in Windows

### ISSUE THREAD

**Issue by tylerohlsen** [jerriep/dotnet-outdated#40]
From a Windows Command Prompt, I get the following exception thrown when running the command: `dotnet outdated > outdated.txt`

```
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at DotNetOutdated.Program.ClearCurrentConsoleLine() in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 227
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 114
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 60```

**Comment by jerriep** [comment]
Duplicate of #28

**Comment by jerriep** [comment]
Version 2.0.0 is now available on NuGet which resolves this issue:
https://www.nuget.org/packages/dotnet-outdated/2.0.0
