### ISSUE TITLE
Allow option to specify Nuget feed to use

### ISSUE THREAD

**Issue by jerriep** [jerriep/dotnet-outdated#8]
Should add an option similiar to the `--source` option of the [dotnet add package](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package) command to specify the NuGet feed to use

**Comment by PaitoAnderson** [comment]
Just to add to this, could it perhaps read the `.nuget/nuget.config` file and use the feeds there? Here's what happens to me when checking for updates for a package on a private feed.

```
  Telerik.UI.for.AspNet.Core ...
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetOutdated.Services.NuGetPackageResolutionService.ResolvePackageVersions(String package, List`1 sources, VersionRange currentVersionRange, VersionLock versionLock, PrereleaseReporting prerelease) in C:\projects\dotnet-outdated\src\DotNetOutdated\Services\NuGetPackageResolutionService.cs:line 27
   at DotNetOutdated.Program.ReportDependency(IConsole console, Dependency dependency, List`1 sources, Int32 indentLevel) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 161
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 122
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 48
```

**Comment by jerriep** [comment]
@PaitoAnderson Actually, it should pick it up automatically already. I have tested against a private MyGet feed and it works. I think this may be related to something else related to the Telerik NuGet feed.

Please run the following command for me from that project directory:

```
dotnet msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=graph.dg
```

Check the resulting `graph.dg` file and see whether the Telerik feed is listed under the `sources` node for the project in question.

**Comment by PaitoAnderson** [comment]
Oh ok, I didn't mean to hijack this issue then.

Interestingly enough, it's not listed:
```
"sources": {
    "C:\\Program Files (x86)\\Microsoft SDKs\\NuGetPackages\\": {},
    "https://api.nuget.org/v3/index.json": {},
    "https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json": {}
},
```

I wonder if that's more of a problem with my solution/project setup then:
```
src
|-- .nuget
|    |-- nuget.config
+-- WebApp.WebHost
|    |-- WebApp.WebHost.csproj
+-- WebApp.sln
```

**Comment by jerriep** [comment]
No worries, you did not hijack the issue 😉 If there is an issue I would like to get it solved. One thing that is a bug for sure is that there is a bug in that a NullReferenceException can occur when I cannot resolve the package reference for some reason. 

At the very least I should handle that better. I will create a separate issue for that.

As for why your Telerik feed is not showing up, that is an interesting problem and I would like to get behind the cause of that. 

Where and how did you register it?

**Comment by PaitoAnderson** [comment]
I'm pretty sure I just did the `NuGet Sources Add` command, as described here:
https://docs.telerik.com/aspnet-mvc/getting-started/nuget-install

However I might have found the issue, this package is actually saved locally:
![image](https://user-images.githubusercontent.com/4108718/40789657-f0d84726-64c0-11e8-9af6-09b9e42abbc5.png)

I hope this helps...

**Comment by jerriep** [comment]
@PaitoAnderson Yeah, this seems like an interesting one.

It will require some investigation, so I would like to ask you yo please open a new issue for this. Also, please add the information you have already supplied again on that issue so we can try and figure it out.

Apologies for the double work, but it will be easier to track this as a separate issue as it is different from the original purpose of this current issue.

**Comment by jerriep** [comment]
@PaitoAnderson You bug is now tracked with #22

**Comment by jerriep** [comment]
Closing issue as **dotnet-outdated** now respects the normal [NuGet configuration behaviour](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior). If an "extra" NuGet feed is to be specified, it can be added in the project-level Nuget.config file.

@PaitoAnderson BTW, version 1.2 now [supports secure feeds](https://github.com/jerriep/dotnet-outdated#working-with-secure-feeds), so you can give it a spin.
