### ISSUE TITLE
NullReferenceException in DotNetOutdated.Services.NuGetPackageResolutionService.ResolvePackageVersions

### ISSUE THREAD

**Issue by tjrobinson** [jerriep/dotnet-outdated#96]
The solution I'm running it on uses the new SDK project format and has a mixture of `netcoreapp2.1`, `netstandard2.0` and `net462`. It's closed source so I can't link to the source unfortunately.

```
dotnet outdated --version
A .NET Core global tool to list outdated Nuget packages.
2.0.0-rtm.94+c1f498a4b8653baa5b0b17aaec7ac6d9f4cc4181
```

```dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.5 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
```
dotnet outdated
Analyzing dependencies for Empactis.HRCM.Commands [.NETFramework,Version=v4.6.2] (1/31)
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetOutdated.Services.NuGetPackageResolutionService.ResolvePackageVersions(String packageName, NuGetVersion referencedVersion, List`1 sources, VersionRange currentVersionRange, VersionLock versionLock, PrereleaseReporting prerelease, NuGetFramework targetFrameworkName, String projectFilePath) in C:\projects\dotnet-outdated\src\DotNetOutdated\Services\NuGetPackageResolutionService.cs:line 24
   at DotNetOutdated.Program.AnalyzeDependencies(List`1 projects, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 341
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 147
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at DotNetOutdated.Program.Main(String[] args) in C:\projects\dotnet-outdated\src\DotNetOutdated\Program.cs:line 73
```

Thanks.

**Comment by jerriep** [comment]
@tjrobinson Can you please attach the offending `.csproj` file for that `Empactis.HRCM.Commands` project?

I don't want any of the source files, just the project file.

Also, have you configured any private NuGet feeds by any chance?

**Comment by tjrobinson** [comment]
Thanks for getting back to me, here's the `.csproj`:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net462</TargetFrameworks>
    <AssemblyName>Empactis.HRCM.Commands</AssemblyName>
    <PackageId>Empactis.HRCM.Commands</PackageId>
    <NoWarn>NU1603,NU1701,NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Empactis.HRCM.Data\Empactis.HRCM.Data.csproj" />
    <ProjectReference Include="..\Empactis.HRCM.Shared\Empactis.HRCM.Shared.csproj" />
    <ProjectReference Include="..\Empactis.HRCM.Workflow\Empactis.HRCM.Workflow.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="7.0.1" />
    <PackageReference Include="Empactis.Data.Querying" Version="1.1.410" />
    <PackageReference Include="Empactis.Sdk.Cryptography" Version="1.1.410" />
    <PackageReference Include="Empactis.Sdk.Notifications" Version="1.1.410" />
    <PackageReference Include="Empactis.Sdk.Security.ServiceAuth" Version="1.1.410" />
    <PackageReference Include="Empactis.Sdk.Shared" Version="1.1.410" />
    <PackageReference Include="Empactis.Sdk.Storage" Version="1.1.410" />
    <PackageReference Include="Empactis.Sdk.WordTemplateMapper" Version="1.1.410" />
    <PackageReference Include="Enumeration.dll" Version="2.0.3" />
    <PackageReference Include="FluentValidation" Version="8.0.100" />
    <PackageReference Include="Hangfire" Version="1.6.20" />
    <PackageReference Include="Hangfire.Core" Version="1.6.20" />
    <PackageReference Include="HtmlAgilityPack" Version="1.8.9" />
    <PackageReference Include="MediatR" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="2.1.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="2.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.19.8" />
    <PackageReference Include="Microsoft.WindowsAzure.ConfigurationManager" Version="3.2.3" />
    <PackageReference Include="morelinq" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
    <PackageReference Include="SerilogTimings" Version="2.2.0" />
    <PackageReference Include="SharpZipLib" Version="1.0.0" />
    <PackageReference Include="StructureMap" Version="4.7.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.2" />
    <PackageReference Include="System.IO.Packaging" Version="4.5.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.3" />
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.2" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
```

And yes, we have a private NuGet feed, `Nuget.config` as below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Empactis MyGet" value="https://www.myget.org/F/empactis/auth/[omitted]/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by jerriep** [comment]
@tjrobinson This is now available in V2.1.0 on NuGet

**Comment by tjrobinson** [comment]
@jerriep Thanks, that works now 👍 

Interestingly it's now struggling to find `xunit.runner.visualstudio`, but only for one of the project.

Truncated output:

```
» Empactis.HRCM.Shared.Tests
  [.NETCoreApp,Version=v2.1]
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NET.Test.Sdk                           15.8.0 -> 15.9.0
  xunit                                            2.4.0  -> 2.4.1
  xunit.runner.visualstudio                        2.4.0  -> 2.4.1

» Empactis.HRCM.Tests
  [.NETFramework,Version=v4.6.2]
  Empactis.Sdk.Testing                             1.1.410 -> 1.1.419
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8  -> 4.3.0
  Microsoft.NET.Test.Sdk                           15.8.0  -> 15.9.0
  xunit                                            2.4.0   -> 2.4.1
  xunit.runner.console                             2.4.0   -> 2.4.1
  xunit.runner.visualstudio                        Cannot determine latest version!

» Empactis.HRCM.Workflow.Tests
  [.NETCoreApp,Version=v2.1]
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NET.Test.Sdk                           15.8.0 -> 15.9.0
  xunit                                            2.4.0  -> 2.4.1
  xunit.runner.console                             2.4.0  -> 2.4.1
  xunit.runner.visualstudio                        2.4.0  -> 2.4.1

Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?
```

The offending `.csproj` is:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462</TargetFrameworks>
    <AssemblyName>Empactis.HRCM.Tests</AssemblyName>
    <NoWarn>NU1608,NU1701,NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Empactis.Sdk.Testing" Version="1.1.410" />
    <PackageReference Include="FluentAssertions" Version="5.4.2" />
    <PackageReference Include="JetBrains.DotMemoryUnit" Version="3.0.20171219.105559" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.19.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" />
    <PackageReference Include="AutoFixture.Xunit2" Version="4.5.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.2" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.console" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.2" />
    <PackageReference Include="Moq" Version="4.10.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Empactis.HRCM.Commands\Empactis.HRCM.Commands.csproj" />
    <ProjectReference Include="..\..\src\Empactis.HRCM.Data\Empactis.HRCM.Data.csproj" />
    <ProjectReference Include="..\..\src\Empactis.HRCM.Shared\Empactis.HRCM.Shared.csproj" />
    <ProjectReference Include="..\..\src\Empactis.HRCM.Workflow\Empactis.HRCM.Workflow.csproj" />
    <ProjectReference Include="..\..\src\Empactis.HRCM\Empactis.HRCM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
```

But the error handling is doing it's job now which is the main thing. Thanks.

**Comment by jerriep** [comment]
@tjrobinson Hmm, that is very strange 😕 Especially since that package resolves fine in other projects, and in that same project there are other packages from NuGet which resolves fine.

Do you consistently get the same result?

FWIW, there is another issue requesting more verbose logging (#85). Once I can get that in place, it may shine more light on what is going here...

**Comment by tjrobinson** [comment]
@jerriep Yea, it's very strange. It happens consistently, only for that project though. I've narrowed it down to it targetting `net462` instead of `netcoreapp2.1`. If I change the project target to `netcoreapp2.1` it works fine.

**Comment by tjrobinson** [comment]
@jerriep Thanks for the update. That is a tricky one - I guess a keeping a list of known dependencies like this is one option but it's not going to work all the time and is obviously work to maintain. It could be an option for popular packages though?

**Comment by jerriep** [comment]
I believe the latest version pre-release build on MyGet solves it by checking for the `DevelopmentDependency` flag in the `.nuspec` file. You can give it a try by installing it with the following command

```
dotnet tool install -g dotnet-outdated --version 2.2.0-pre.191 --add-source https://www.myget.org/F/jerriep/api/v3/index.json
```

Remember to uninstall your current version first.

**Comment by tjrobinson** [comment]
That didn't go very well unfortunately, log below:

```
C:\Code\Empactis\CaseManager [develop ≡]> dotnet tool uninstall -g dotnet-outdated
Tool 'dotnet-outdated' (version '2.1.0') was successfully uninstalled.
C:\Code\Empactis\CaseManager [develop ≡]> dotnet tool install -g dotnet-outdated --version 2.2.0-pre.191 --add-source https://www.myget.org/F/jerriep/api/v3/index.json
You can invoke the tool using the following command: dotnet-outdated
Tool 'dotnet-outdated' (version '2.2.0-pre.191') was successfully installed.
C:\Code\Empactis\CaseManager [develop ≡]> dotnet outdated
» Empactis.HRCM.Commands
  [.NETFramework,Version=v4.6.2]
  Hangfire                                         1.6.20 -> 1.6.21
  Hangfire.Core                                    1.6.20 -> 1.6.21
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.WindowsAzure.ConfigurationManager      Cannot determine latest version!
  [.NETStandard,Version=v2.0]
  Hangfire                                         1.6.20 -> 1.6.21
  Hangfire.Core                                    1.6.20 -> 1.6.21
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.WindowsAzure.ConfigurationManager      Cannot determine latest version!

» Empactis.HRCM.Console
  [.NETCoreApp,Version=v2.1]
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0

» Empactis.HRCM.Data
  [.NETFramework,Version=v4.6.2]
  Metrics.NET                                      Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NETCore.Platforms                      Cannot determine latest version!
  [.NETStandard,Version=v2.0]
  Metrics.NET                                      Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NETCore.Platforms                      Cannot determine latest version!

» Empactis.HRCM.Shared
  [.NETFramework,Version=v4.6.2]
  HangFire                                         1.6.20       -> 1.6.21
  Microsoft.Bcl.Build                              Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8       -> 4.3.0
  ReSharper.Annotations                            Cannot determine latest version!
  [.NETStandard,Version=v2.0]
  HangFire                                         1.6.20       -> 1.6.21
  Microsoft.Bcl.Build                              Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8       -> 4.3.0
  ReSharper.Annotations                            Cannot determine latest version!

» Empactis.HRCM.WebJobs
  [.NETCoreApp,Version=v2.1]
  -- No outdated dependencies --

» Empactis.HRCM.Workflow
  [.NETFramework,Version=v4.6.2]
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  [.NETStandard,Version=v2.0]
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0

» Empactis.HRCM
  [.NETFramework,Version=v4.6.2]
  Hangfire                                         1.6.20 -> 1.6.21
  Hangfire.AspNetCore                              1.6.20 -> 1.6.21
  Hangfire.SqlServer                               1.6.20 -> 1.6.21
  Metrics.NET                                      Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NETCore.Platforms                      Cannot determine latest version!
  Microsoft.WindowsAzure.ConfigurationManager      Cannot determine latest version!

» Empactis.HRCM.Commands.Tests
  [.NETCoreApp,Version=v2.1]
  FluentAssertions.Analyzers                       Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NETCore.Platforms                      Cannot determine latest version!

» Empactis.HRCM.Shared.Tests
  [.NETCoreApp,Version=v2.1]
  FluentAssertions.Analyzers                       Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NETCore.Platforms                      Cannot determine latest version!
  xunit.analyzers                                  Cannot determine latest version!

» Empactis.HRCM.Tests
  [.NETFramework,Version=v4.6.2]
  JetBrains.DotMemoryUnit                          Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8              -> 4.3.0

» Empactis.HRCM.Workflow.Tests
  [.NETCoreApp,Version=v2.1]
  FluentAssertions.Analyzers                       Cannot determine latest version!
  Microsoft.IdentityModel.Clients.ActiveDirectory  3.19.8 -> 4.3.0
  Microsoft.NETCore.Platforms                      Cannot determine latest version!
  Microsoft.WindowsAzure.ConfigurationManager      Cannot determine latest version!
  xunit.analyzers                                  Cannot determine latest version!

Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?

Version color legend:
<red>   : Major version update or pre-release version. Possible breaking changes.
<yellow>: Minor version update. Backwards-compatible features added.
<green> : Patch version update. Backwards-compatible bug fixes.

You can upgrade packages to the latest version by passing the -u or -u:prompt option.
```

**Comment by tjrobinson** [comment]
I ran it twice and diffed the results, exactly the same.
